### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by alcazes** [adobe/reactor-packager#18]
When I run `npx @adobe/reactor-packager`, a zip file is generated but it is empty and in the console I get this:
`Maximum call stack size exceeded`. It literally just display this without any error.

Any idea what I am doing wrong? 

Thanks

**Comment by alcazes** [comment]
If I zip it myself and upload it Adobe Launch, the build is stuck: https://experience.adobe.com/#/@rbs/launch/companies/COe5253eb028b44a8dbe0d4830477b7be6/properties/PRedc7aef94c774623b0527d1d268b24d0/publishing/LB13ade1ab879b4ee0a7fd1d7b76ea38cc

**Comment by alcazes** [comment]
Closing this as it does not seem anybody is monitoring these issues.

Issue seems that Adobe Launch packager does not handle well instances where extension contains several .js files that make reference to each other using require. At some point Maximum call stack size exceeded will happen.

Solution was to move all of the functions into one files instead of splitting them in multiple files.

**Comment by spencerroan** [comment]
@alcazes, these issues are indeed monitored, though we don't have a guaranteed response time.

The team as a whole has been enjoying some much needed time off from an unprecedented year celebrating Thanksgiving.
This error will be prioritized in our next triage.

**Comment by thebenrob** [comment]
@alcazes, @jhicken from our eng team has suggested that you double-check all the paths as well as adding the .js to all your require statements.  Apparently many of the packagers out there have some included magic to resolve ambiguous file paths and automatically add file extensions, but that the packager is not one of them.
But there should be no maximum to the number of files that an extension package can contain.

**Comment by Aaronius** [comment]
> Apparently many of the packagers out there have some included magic to resolve ambiguous file paths and automatically add file extensions, but that the packager is not one of them.

The packager allows for not specifying the extension: https://github.com/adobe/reactor-packager/blob/c4571b9e47d77ab8ca004d9eca54a3a0d3702a69/tasks/helpers/getPackagePaths.js#L39-L40

If we're seeing different behavior, it's a bug.

**Comment by jhicken** [comment]
Thanks @Aaronius

**Comment by brenthosie** [comment]
@alcazes Do you have a way to reproduce this and share it with me so I can diagnose what's going on?

**Comment by alcazes** [comment]
@brenthosie I have created the following support ticket with Adobe https://adminconsole.adobe.com/C50417FE52CB33480A490D4C@AdobeOrg/support/support-cases/E-000357711 and attached the zip file which contains the project that created the issue at the time. 

I have now moved away from using the structure for the same project and fully refactored it. It now works just fine.
