### ISSUE TITLE
core-js deprecated warning when installing

### ISSUE THREAD

**Issue by yuhui** [adobe/reactor-packager#19]
When running `npx @adobe/reactor-packager` for the first time, a deprecated warning for `core-js` is listed.

### Expected Behaviour
No warnings are listed.

### Actual Behaviour
Warnings appear.

### Reproduce Scenario (including but not limited to)

macOS Big Sur 11.0.1
node 15.2.1
npm 7.0.8

`node` and `npm` installed with `brew`.

#### Steps to Reproduce

1. Run `npx @adobe/reactor-packager`

#### Sample Code that illustrates the problem

```
yuhui@computer launch-extension-folder % npx @adobe/reactor-packager
Need to install the following packages:
  @adobe/reactor-packager
Ok to proceed? (y) y
npm WARN deprecated core-js@2.6.12: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

**Comment by brenthosie** [comment]
@yuhui Thanks for the report, I will look into bumping the dependency causing the problem soon.

**Comment by yuhui** [comment]
Updated set of warnings

Environment:
node 15.8.0
npm 7.5.4

```
npm WARN deprecated core-js@2.6.12: core-js@<3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
```

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL

**Comment by thebenrob** [comment]
@adobe export issue to Jira project PDCL
