### ISSUE TITLE
require within comments are not ignored

### ISSUE THREAD

**Issue by stewartschillingsdi** [adobe/reactor-packager#8]
If I have the following in my extension code (src/lib/**/*.js ) :
```
var util = require('./util');
//require('./foobar');
```
When running reactor-packager, (assuming that ./foobar.js does not exist), I would get the error
Error: ENOENT: no such file or directory, open 'src/lib/packages/foobar.js'
    at Object.openSync (fs.js:443:3)
    at Object.readFileSync (fs.js:348:35)
...

I traced this down to https://github.com/Adobe-Marketing-Cloud/reactor-packager/blob/master/tasks/helpers/getPackagePaths.js
and specifically to the use of `matchRequires = require('match-requires');` on line 34   `matchRequires(source)`.  

From the usage description on https://github.com/jonschlinkert/match-requires you should be able to set the 2nd parameter to true to enable stripping of comments as `matchRequires(source, true)`.  I gave it a shot but it ended up causing a deeper error in `strip-comments` which is pulled in by `match-requires`.  

Anyway,  although I didn't fix the issue, I figured that I'd raise it in case someone else thinks it's worth fixing.

**Comment by Aaronius** [comment]
Thanks @stewartschillingsdi. Do you you still have the error that you saw coming from the `strip-comments` lib? It might be helpful if/when we decide to fix this.

**Comment by stewartschillingsdi** [comment]
Yep.  From strip-comments v1.0.2
/repos/.../node_modules/@adobe/reactor-packager/node_modules/strip-comments/index.js:144
      throw err;
      ^

SyntaxError: Unexpected token (1:0)
